apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  resourceName: terminus-scheduler
  resourceNamespace: terminus
profiles:
  - schedulerName: terminus-scheduler
    plugins:
      filter:
        enabled:
          - name: terminus-scheduler
      score:
        enabled:
          - name: terminus-scheduler
            weight: 1
    pluginConfig:
      - name: terminus-scheduler
        args:
          oversubscriptionRatio: 1.5