apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  resourceName: terminus-scheduler
  resourceNamespace: terminus
profiles:
  - schedulerName: terminus-scheduler
    plugins:
      filter:
        enabled:
          - name: terminus-scheduler
      score:
        enabled:
          - name: terminus-scheduler
            weight: 1
    pluginConfig:
      - name: terminus-scheduler
        args:
          oversubscriptionRatio: 1.5
          useAI: false
          aiWeightRatio: 50
          modelType: "OPENAI"
          modelName: "gpt-3.5-turbo"
          openAIAPIKey: ""
          openAIAPIURL: "https://api.openai.com/v1"