apiVersion: v1
kind: ConfigMap
metadata:
  name: terminus-scheduler-config
  labels:
    {{- include "terminus.labels" . | nindent 4 }}
data:
  terminus-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: terminus-scheduler
      resourceNamespace: {{ .Release.Namespace }}
    profiles:
      - schedulerName: terminus-scheduler
        plugins:
          filter:
            enabled:
              - name: terminus-scheduler
          score:
            enabled:
              - name: terminus-scheduler
                weight: 1
        pluginConfig:
          - name: terminus-scheduler
            args:
              oversubscriptionRatio: {{ .Values.scheduler.oversubscriptionRatio }}
