images:
  enforcer:
    repository: ghcr.io/terminus/enforcer
    tag: latest
    pullPolicy: IfNotPresent
  scheduler:
    repository: ghcr.io/terminus/scheduler
    tag: latest
    pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: "terminus-admin"

scheduler:
  enable: true
  replicas: 3
  logLevel: "4"
  oversubscriptionRatio: 1.5
  leaderElect: true
  useAI: false
  aiWeightRatio: 50
  modelType: "OPENAI"
  modelName: "gpt-3.5-turbo"
  openAIAPIKey: ""
  openAIAPIURL: "https://api.openai.com/v1"

enforcer:
  logLevel: "4"
  priorityClassName: system-node-critical
  containerdBasePath: /var/lib/containerd

service:
  type: ClusterIP
  port: 9201
