apiVersion: v1
kind: Service
metadata:
  name: terminus-exporter-svc
  labels:
    {{- include "terminus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: terminus-enforcer
  ports:
    - name: metrics-port
      port: {{ .Values.service.port }}
      targetPort: 9201
      protocol: TCP
