apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: terminus-scraper
  namespace: terminus
  labels:
    app: terminus-exporter
spec:
  selector:
    matchLabels:
      app: terminus
  endpoints:
    - port: metrics-port
      path: /metrics
      interval: 15s
      honorLabels: true